[".oh-my-zsh/custom/plugins/fzf-tab"]
type = "git-repo"
url = "https://github.com/Aloxaf/fzf-tab.git"

[".oh-my-zsh/custom/plugins/zsh-wakatime"]
type = "git-repo"
url = "https://github.com/Aloxaf/zsh-wakatime.git"

[".oh-my-zsh/custom/plugins/zsh-256color"]
type = "git-repo"
url = "https://github.com/Aloxaf/zsh-wakatime.git"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/Aloxaf/zsh-autosuggestions.git"

[".oh-my-zsh/custom/plugins/zsh-better-npm-completion"]
type = "git-repo"
url = "https://github.com/lukechilds/zsh-better-npm-completion.git"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"

[".config/tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"

[".config/yazi/theme.toml"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/yazi/main/themes/mocha/catppuccin-mocha-lavender.toml"

[".config/kitty/theme.conf"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/kitty/refs/heads/main/themes/mocha.conf"
